name: PR. Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    env:
      Solution_Name: Translumo.sln
      SkipBinariesExtract: true   # Skip download additional binaries, those are set in cproj as a prebuilt step
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Build the application
      run: dotnet build $env:Solution_Name /p:Configuration=Release
